### ISSUE TITLE
Game Logic

### ISSUE THREAD

**Issue by amutzaba** [K31THSTONE/Senior-Software-Design-II#8]
When it comes to the gameplay, we will need to have the proper rules set in place. This could include numbers of kills, a timer for the game, etc.

**Comment by amutzaba** [comment]
This has been a work in progress alongside the logic which will end the game

**Comment by K31THSTONE** [comment]
Game now ends on a kill limit that we set in the code. Puts player back at lobby scene.

**Comment by K31THSTONE** [comment]
Game logic is now fully implemented. Tweaks and improvements, not creation of game logic, is all that's left
